name: Check

on: [push, pull_request, workflow_dispatch]

jobs:
  flake-check:
    name: Check flake expressions
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix flake check --keep-going --show-trace

  build-vanaheim:
    name: Build vanaheim system
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix-fast-build --skip-cached --no-nom \
          --flake ".#nixosConfigurations.vanaheim.config.system.build.toplevel"
