name: Check

on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  flake-check:
    name: Check flake expressions
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix flake check --keep-going --show-trace

  build-hosts:
    name: Build ${{ matrix.host }} system
    uses: ./.github/workflows/prelude.yml
    strategy:
      fail-fast: false
      matrix:
        host:
          - alfheim
          - vivo
          - vanaheim
          - minimal
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix-fast-build --skip-cached --no-nom \
          --flake ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
