name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Open flake.lock update PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f
        with:
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
          diagnostic-endpoint: ""
          extra-conf: |
            experimental-features = nix-command flakes
            allow-import-from-derivation = false

      - name: Open update pull request
        uses: DeterminateSystems/update-flake-lock@c5930b397a673a70ca70be06020e943aeac310a1
        with:
          pr-title: "flake.lock: Update"
